name: Test Manual Workflow

on:
    workflow_dispatch:
      inputs:
        Environnement:
          description: 'The Environnement I need to deploy on'
          required: true
          default: '/dev'

jobs:
    manual-jobs:
      runs-on: ubuntu-latest

      steps:
        - name: Exemple
          run: echo "Mon exemple"

    